apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pdb-mirror-data
  name: pdb-mirror-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
